Repository OCA/account-reconcile, pull requests merged in 2021-11, with the labels that each got.

#417 [14.0][FIX] account_reconcile_widget : Fix foreign_currency_id vs currency_id on bank statement
  account_reconciliation_widget/models/account_bank_statement.py
  account_reconciliation_widget/models/reconciliation_widget.py
Labels: bot is merging ⏳

#361 [14.0][MIG] account_move_reconcile_helper: Migration to 14.0
  account_move_reconcile_helper/README.rst
  account_move_reconcile_helper/__init__.py
  account_move_reconcile_helper/__manifest__.py
  account_move_reconcile_helper/i18n/account_move_reconcile_helper.pot
  account_move_reconcile_helper/i18n/es.po
  account_move_reconcile_helper/i18n/fr.po
  account_move_reconcile_helper/i18n/hr.po
  account_move_reconcile_helper/models/__init__.py
  account_move_reconcile_helper/models/account_move_line.py
  account_move_reconcile_helper/readme/CONTRIBUTORS.rst
  account_move_reconcile_helper/readme/DESCRIPTION.rst
  account_move_reconcile_helper/static/description/icon.png
  account_move_reconcile_helper/static/description/index.html
  account_move_reconcile_helper/static/docs/journal_items.png
  account_move_reconcile_helper/tests/__init__.py
  account_move_reconcile_helper/tests/test_account_move_reconcile_helper.py
  account_move_reconcile_helper/views/account_move_line.xml
  setup/account_move_reconcile_helper/odoo/addons/account_move_reconcile_helper
  setup/account_move_reconcile_helper/setup.py
Labels: needs fixing, approved, ready to merge, bot is merging ⏳

#301 [13.0][MIG] account_move_reconcile_helper
  account_move_reconcile_helper/README.rst
  account_move_reconcile_helper/__init__.py
  account_move_reconcile_helper/__manifest__.py
  account_move_reconcile_helper/i18n/account_move_reconcile_helper.pot
  account_move_reconcile_helper/i18n/es.po
  account_move_reconcile_helper/i18n/fr.po
  account_move_reconcile_helper/i18n/hr.po
  account_move_reconcile_helper/models/__init__.py
  account_move_reconcile_helper/models/account_move_line.py
  account_move_reconcile_helper/readme/CONTRIBUTORS.rst
  account_move_reconcile_helper/readme/DESCRIPTION.rst
  account_move_reconcile_helper/static/description/icon.png
  account_move_reconcile_helper/static/description/index.html
  account_move_reconcile_helper/static/docs/journal_items.png
  account_move_reconcile_helper/tests/__init__.py
  account_move_reconcile_helper/tests/test_account_move_reconcile_helper.py
  account_move_reconcile_helper/views/account_move_line.xml
  oca_dependencies.txt
  setup/account_move_reconcile_helper/odoo/addons/account_move_reconcile_helper
  setup/account_move_reconcile_helper/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#252 [IMP] account_move_base_import: don't break without xlrd, add it to dependencies
  account_move_base_import/__manifest__.py
  account_move_base_import/parser/file_parser.py
Labels: needs review, approved, bot is merging ⏳
