Repository OCA/account-reconcile, pull requests merged in 2022-07, with the labels that each got.

#480 [FIX] account_move_reconcile_forbid_cancel: make it compatible with tests of other modules
  account_move_reconcile_forbid_cancel/models/account_move.py
  account_move_reconcile_forbid_cancel/tests/test_account_move_reconcile_forbid_cancel.py
Labels: bot is merging ⏳

#382 [14.0] account_reconciliation_widget: remove payment_id <> false
  account_reconciliation_widget/__init__.py
  account_reconciliation_widget/__manifest__.py
  account_reconciliation_widget/wizards/__init__.py
  account_reconciliation_widget/wizards/res_config_settings.py
  account_reconciliation_widget/wizards/res_config_settings_views.xml
Labels: bot is merging ⏳

#481 [15.0][IMP] account_reconciliation_widget: Add date field account_bank_reconciliation_start on accounting config page
  account_reconciliation_widget/__init__.py
  account_reconciliation_widget/__manifest__.py
  account_reconciliation_widget/wizards/__init__.py
  account_reconciliation_widget/wizards/res_config_settings.py
  account_reconciliation_widget/wizards/res_config_settings_views.xml
Labels: bot is merging ⏳

#483 [14][FIX] (fix the previous PR #420) account_reconcile_widget: value cleaning & decimal separator choice
  account_reconciliation_widget/static/src/js/reconciliation/reconciliation_model.js
Labels: bot is merging ⏳

#482 [15][IMP] FW port #420 (account_reconcile_widget: value cleaning & decimal separator choice)
  account_reconciliation_widget/static/src/js/reconciliation/reconciliation_model.js
Labels: approved, bot is merging ⏳

#471 [15.0][MIG] account_partner_reconcile
  account_partner_reconcile/README.rst
  account_partner_reconcile/__init__.py
  account_partner_reconcile/__manifest__.py
  account_partner_reconcile/i18n/account_partner_reconcile.pot
  account_partner_reconcile/i18n/es.po
  account_partner_reconcile/i18n/es_AR.po
  account_partner_reconcile/i18n/fr.po
  account_partner_reconcile/i18n/fr_FR.po
  account_partner_reconcile/i18n/pt.po
  account_partner_reconcile/models/__init__.py
  account_partner_reconcile/models/res_partner.py
  account_partner_reconcile/readme/CONFIGURE.rst
  account_partner_reconcile/readme/CONTRIBUTORS.rst
  account_partner_reconcile/readme/DESCRIPTION.rst
  account_partner_reconcile/readme/USAGE.rst
  account_partner_reconcile/static/description/icon.png
  account_partner_reconcile/static/description/index.html
  account_partner_reconcile/tests/__init__.py
  account_partner_reconcile/tests/test_account_partner_reconcile.py
  account_partner_reconcile/views/res_partner_view.xml
  setup/account_partner_reconcile/odoo/addons/account_partner_reconcile
  setup/account_partner_reconcile/setup.py
Labels: approved, ready to merge, bot is merging ⏳
