Repository OCA/account-reconcile, pull requests merged in 2022-12, with the labels that each got.

#489 [14.0][IMP] account_reconcile_reconciliation_date: reconciliation date should not be copied
  account_reconcile_reconciliation_date/models/account_move.py
  account_reconcile_reconciliation_date/models/account_payment.py
Labels: bot is merging ⏳, stale

#508 [15.0][MIG] account_move_reconcile_forbid_cancel: Migration to 15.0
  account_move_reconcile_forbid_cancel/README.rst
  account_move_reconcile_forbid_cancel/__init__.py
  account_move_reconcile_forbid_cancel/__manifest__.py
  account_move_reconcile_forbid_cancel/i18n/account_move_reconcile_forbid_cancel.pot
  account_move_reconcile_forbid_cancel/i18n/es.po
  account_move_reconcile_forbid_cancel/models/__init__.py
  account_move_reconcile_forbid_cancel/models/account_move.py
  account_move_reconcile_forbid_cancel/readme/CONTRIBUTORS.rst
  account_move_reconcile_forbid_cancel/readme/DESCRIPTION.rst
  account_move_reconcile_forbid_cancel/readme/USAGE.rst
  account_move_reconcile_forbid_cancel/static/description/icon.png
  account_move_reconcile_forbid_cancel/static/description/index.html
  account_move_reconcile_forbid_cancel/tests/__init__.py
  account_move_reconcile_forbid_cancel/tests/test_account_move_reconcile_forbid_cancel.py
  setup/account_move_reconcile_forbid_cancel/odoo/addons/account_move_reconcile_forbid_cancel
  setup/account_move_reconcile_forbid_cancel/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#475 [14.0][FIX] account_mass_reconcile: reuse currency rate in test (forward port)
  account_mass_reconcile/tests/test_scenario_reconcile.py
Labels: approved, bot is merging ⏳
