Repository OCA/account-reconcile, pull requests merged in 2022-06, with the labels that each got.

#264 [12.0][MIG] account_mass_reconcile_by_purchase_line
  account_banking_reconciliation/__manifest__.py
  account_mass_reconcile/tests/test_scenario_reconcile.py
  account_mass_reconcile_by_purchase_line/README.rst
  account_mass_reconcile_by_purchase_line/__init__.py
  account_mass_reconcile_by_purchase_line/__manifest__.py
  account_mass_reconcile_by_purchase_line/i18n/account_mass_reconcile_by_purchase_line.pot
  account_mass_reconcile_by_purchase_line/i18n/ar.po
  account_mass_reconcile_by_purchase_line/models/__init__.py
  account_mass_reconcile_by_purchase_line/models/advanced_reconciliation.py
  account_mass_reconcile_by_purchase_line/models/base_advanced_reconciliation.py
  account_mass_reconcile_by_purchase_line/models/mass_reconcile.py
  account_mass_reconcile_by_purchase_line/readme/CONTRIBUTORS.rst
  account_mass_reconcile_by_purchase_line/readme/DESCRIPTION.rst
  account_mass_reconcile_by_purchase_line/readme/USAGE.rst
  account_mass_reconcile_by_purchase_line/static/description/icon.png
  account_mass_reconcile_by_purchase_line/views/mass_reconcile.xml
Labels: approved, bot is merging ⏳

#398 [13.0][MIG] account_mass_reconcile_by_purchase_line
  .travis.yml
  account_mass_reconcile/tests/test_scenario_reconcile.py
  account_mass_reconcile_by_purchase_line/README.rst
  account_mass_reconcile_by_purchase_line/__init__.py
  account_mass_reconcile_by_purchase_line/__manifest__.py
  account_mass_reconcile_by_purchase_line/i18n/account_mass_reconcile_by_purchase_line.pot
  account_mass_reconcile_by_purchase_line/i18n/ar.po
  account_mass_reconcile_by_purchase_line/models/__init__.py
  account_mass_reconcile_by_purchase_line/models/advanced_reconciliation.py
  account_mass_reconcile_by_purchase_line/models/base_advanced_reconciliation.py
  account_mass_reconcile_by_purchase_line/models/mass_reconcile.py
  account_mass_reconcile_by_purchase_line/readme/CONTRIBUTORS.rst
  account_mass_reconcile_by_purchase_line/readme/DESCRIPTION.rst
  account_mass_reconcile_by_purchase_line/readme/USAGE.rst
  account_mass_reconcile_by_purchase_line/static/description/icon.png
  account_mass_reconcile_by_purchase_line/views/mass_reconcile.xml
  account_reconcile_model_strict_match_amount/models/account_reconcile_model.py
  account_reconcile_model_strict_match_amount/tests/test_account_reconcile_model_strict_match_amount.py
  account_reconcile_restrict_partner_mismatch/tests/test_reconciliation.py
  setup/account_mass_reconcile_by_purchase_line/odoo/addons/account_mass_reconcile_by_purchase_line
  setup/account_mass_reconcile_by_purchase_line/setup.py
Labels: approved, bot is merging ⏳

#470 [13.0][IMP] update copier from template
  .copier-answers.yml
  .eslintrc.yml
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .gitignore
  .isort.cfg
  .pre-commit-config.yaml
  .prettierrc.yml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  LICENSE
  README.md
  account_reconcile_restrict_partner_mismatch/__manifest__.py
  account_skip_bank_reconciliation/__manifest__.py
  bank_statement_journal_items/__manifest__.py
Labels: approved

#473 [13.0][ADD] account_move_reconcile_forbid_cancel
  account_move_reconcile_forbid_cancel/README.rst
  account_move_reconcile_forbid_cancel/__init__.py
  account_move_reconcile_forbid_cancel/__manifest__.py
  account_move_reconcile_forbid_cancel/i18n/account_move_reconcile_forbid_cancel.pot
  account_move_reconcile_forbid_cancel/i18n/es.po
  account_move_reconcile_forbid_cancel/models/__init__.py
  account_move_reconcile_forbid_cancel/models/account_move.py
  account_move_reconcile_forbid_cancel/readme/CONTRIBUTORS.rst
  account_move_reconcile_forbid_cancel/readme/DESCRIPTION.rst
  account_move_reconcile_forbid_cancel/readme/USAGE.rst
  account_move_reconcile_forbid_cancel/static/description/index.html
  account_move_reconcile_forbid_cancel/tests/__init__.py
  account_move_reconcile_forbid_cancel/tests/test_account_move_reconcile_forbid_cancel.py
  setup/account_move_reconcile_forbid_cancel/odoo/addons/account_move_reconcile_forbid_cancel
  setup/account_move_reconcile_forbid_cancel/setup.py
Labels: bot is merging ⏳
