Repository OCA/account-reconcile, pull requests merged in 2023-02, with the labels that each got.

#444 [14.0][FIX] account_reconciliation_widget: in case of manual operation with…
  account_reconciliation_widget/models/account_bank_statement.py
Labels: approved, bot is merging ⏳

#514 [16.0][ADD] module account_statement_base
  account_statement_base/README.rst
  account_statement_base/__init__.py
  account_statement_base/__manifest__.py
  account_statement_base/readme/CONTRIBUTORS.rst
  account_statement_base/readme/DESCRIPTION.rst
  account_statement_base/views/account_bank_statement_line.xml
  setup/account_statement_base/odoo/addons/account_statement_base
  setup/account_statement_base/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#521 [15.0][FIX] account_reconciliation_widget: Analytic in manual operation
  account_reconciliation_widget/models/account_bank_statement.py
Labels: bot is merging ⏳
