Repository OCA/account-reconcile, pull requests merged in 2023-12, with the labels that each got.

#466 [15.0][MIG] account_move_reconcile_helper
  account_move_reconcile_helper/README.rst
  account_move_reconcile_helper/__init__.py
  account_move_reconcile_helper/__manifest__.py
  account_move_reconcile_helper/i18n/account_move_reconcile_helper.pot
  account_move_reconcile_helper/i18n/es.po
  account_move_reconcile_helper/i18n/fr.po
  account_move_reconcile_helper/i18n/hr.po
  account_move_reconcile_helper/models/__init__.py
  account_move_reconcile_helper/models/account_move_line.py
  account_move_reconcile_helper/readme/CONTRIBUTORS.rst
  account_move_reconcile_helper/readme/DESCRIPTION.rst
  account_move_reconcile_helper/static/description/icon.png
  account_move_reconcile_helper/static/description/index.html
  account_move_reconcile_helper/static/docs/journal_items.png
  account_move_reconcile_helper/tests/__init__.py
  account_move_reconcile_helper/tests/test_account_move_reconcile_helper.py
  account_move_reconcile_helper/views/account_move_line.xml
  setup/account_move_reconcile_helper/odoo/addons/account_move_reconcile_helper
  setup/account_move_reconcile_helper/setup.py
Labels: approved, ready to merge, bot is merging ⏳, stale

#616 [16.0] account_reconcile_oca: improve move line tree view
  account_reconcile_oca/views/account_move_line.xml
Labels: bot is merging ⏳

#613 [16.0][IMP] account_reconcile_oca: Add Reconcile action
  account_reconcile_oca/README.rst
  account_reconcile_oca/__manifest__.py
  account_reconcile_oca/models/__init__.py
  account_reconcile_oca/models/account_account_reconcile.py
  account_reconcile_oca/models/account_bank_statement_line.py
  account_reconcile_oca/models/account_journal.py
  account_reconcile_oca/models/account_move_line.py
  account_reconcile_oca/models/account_reconcile_abstract.py
  account_reconcile_oca/static/description/index.html
  account_reconcile_oca/views/account_account.xml
  account_reconcile_oca/views/account_account_reconcile.xml
  account_reconcile_oca/views/account_bank_statement_line.xml
  account_reconcile_oca/views/account_journal.xml
  account_reconcile_oca/views/account_move.xml
  account_reconcile_oca/views/account_move_line.xml
Labels: approved, bot is merging ⏳
