Repository OCA/account-reconcile, pull requests merged in 2023-10, with the labels that each got.

#598 [15.0][FIX] account_reconciliation_widget: m2x record keyboard navigation
  account_reconciliation_widget/static/src/js/reconciliation/reconciliation_action.js
Labels: approved, bot is merging ⏳

#597 [16.0] account_move_line_reconcile_manual: add write-off models
  account_move_line_reconcile_manual/__init__.py
  account_move_line_reconcile_manual/__manifest__.py
  account_move_line_reconcile_manual/models/__init__.py
  account_move_line_reconcile_manual/models/account_reconcile_manual_model.py
  account_move_line_reconcile_manual/security/ir.model.access.csv
  account_move_line_reconcile_manual/views/account_reconcile_manual_model.xml
  account_move_line_reconcile_manual/wizards/account_move_line_reconcile_manual.py
  account_move_line_reconcile_manual/wizards/account_move_line_reconcile_manual_view.xml
Labels: bot is merging ⏳

#602 [16.0][IMP] account-reconcile : test performance improvement
  account_move_reconcile_forbid_cancel/tests/test_account_move_reconcile_forbid_cancel.py
Labels: bot is merging ⏳

#594 [16.0][IMP] account_reconcile_oca: display partner_name
  account_reconcile_oca/models/account_bank_statement_line.py
Labels: approved, ready to merge, bot is merging ⏳

#601 [15.0][IMP] account-reconcile: test performance improvement
  account_bank_statement_reopen_skip_undo_reconciliation/tests/test_account_bank_statement.py
  account_move_reconcile_forbid_cancel/tests/test_account_move_reconcile_forbid_cancel.py
  account_reconcile_payment_order/tests/test_account_reconcile_payment_order.py
  account_reconciliation_widget/tests/test_reconciliation_widget.py
  account_reconciliation_widget_due_date/tests/test_account_reconciliation_widget_date_due.py
Labels: bot is merging ⏳

#604 [16.0][IMP] account_mass_reconcile: Add 'oldest move line' option on reconc…
  account_mass_reconcile/models/base_reconciliation.py
  account_mass_reconcile/models/mass_reconcile.py
  account_mass_reconcile/models/simple_reconciliation.py
  account_mass_reconcile/readme/DESCRIPTION.rst
  account_mass_reconcile/tests/test_scenario_reconcile.py
Labels: approved, bot is merging ⏳

#606 [14.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  account_mass_reconcile/i18n/account_mass_reconcile.pot
  account_mass_reconcile/views/mass_reconcile.xml
  account_mass_reconcile/views/mass_reconcile_history_view.xml
  account_move_base_import/i18n/account_move_base_import.pot
  account_move_base_import/views/account_move_view.xml
  account_reconcile_restrict_partner_mismatch/i18n/account_reconcile_restrict_partner_mismatch.pot
  account_reconcile_restrict_partner_mismatch/report/account_move_lines_report.xml
  account_reconciliation_widget/views/account_bank_statement_view.xml
  account_reconciliation_widget/views/account_journal_dashboard_view.xml
  account_reconciliation_widget/views/account_view.xml
  account_reconciliation_widget_limit_aml/views/res_config_settings_views.xml
Labels: help wanted, needs review

#552 [16.0][FIX] account_mass_reconcile : fix write-off with today's date
  account_mass_reconcile/models/base_reconciliation.py
  account_mass_reconcile/tests/test_scenario_reconcile.py
Labels: approved, ready to merge, bot is merging ⏳
