Repository OCA/account-reconcile, pull requests merged in 2023-09, with the labels that each got.

#557 [14.0][FIX] Missing dependency `account_reconciliation_widget`
  account_partner_reconcile/__manifest__.py
Labels: bot is merging ⏳

#577 [FIX] account_reconcile_oca: Make it work with foreign currency
  account_reconcile_oca/models/account_account_reconcile.py
  account_reconcile_oca/models/account_bank_statement_line.py
  account_reconcile_oca/models/account_reconcile_abstract.py
  account_reconcile_oca/static/src/js/widgets/reconcile_data_widget.esm.js
  account_reconcile_oca/static/src/xml/reconcile.xml
  account_reconcile_oca/tests/test_bank_account_reconcile.py
  account_reconcile_oca/views/account_account_reconcile.xml
  account_reconcile_oca/views/account_bank_statement_line.xml
  account_reconcile_oca/views/account_move_line.xml
Labels: bot is merging ⏳

#587 [16.0] [IMP] account_reconcile_oca
  account_reconcile_oca/models/account_bank_statement_line.py
  account_reconcile_oca/views/account_bank_statement_line.xml
Labels: approved, ready to merge

#580 [IMP] account_reconcile_oca: Include taxes from models
  account_reconcile_oca/models/account_bank_statement_line.py
  account_reconcile_oca/tests/test_bank_account_reconcile.py
Labels: bot is merging ⏳

#591 [14.0][ADD]account_reconciliation_widget_limit_aml: Filter all account move lines in reconciliation view
  account_reconciliation_widget_limit_aml/__init__.py
  account_reconciliation_widget_limit_aml/__manifest__.py
  account_reconciliation_widget_limit_aml/models/__init__.py
  account_reconciliation_widget_limit_aml/models/reconciliation_widget.py
  account_reconciliation_widget_limit_aml/models/res_company.py
  account_reconciliation_widget_limit_aml/models/res_config_settings.py
  account_reconciliation_widget_limit_aml/readme/CONTRIBUTORS.rst
  account_reconciliation_widget_limit_aml/readme/DESCRIPTION.rst
  account_reconciliation_widget_limit_aml/readme/USAGE.rst
  account_reconciliation_widget_limit_aml/static/description/icon.png
  account_reconciliation_widget_limit_aml/views/res_config_settings_views.xml
  setup/account_reconciliation_widget_limit_aml/odoo/addons/account_reconciliation_widget_limit_aml
  setup/account_reconciliation_widget_limit_aml/setup.py
Labels: approved, bot is merging ⏳

#593 [15.0][MIG] account_reconciliation_widget_limit_aml
  account_reconciliation_widget_limit_aml/README.rst
  account_reconciliation_widget_limit_aml/__init__.py
  account_reconciliation_widget_limit_aml/__manifest__.py
  account_reconciliation_widget_limit_aml/i18n/account_reconciliation_widget_limit_aml.pot
  account_reconciliation_widget_limit_aml/models/__init__.py
  account_reconciliation_widget_limit_aml/models/reconciliation_widget.py
  account_reconciliation_widget_limit_aml/models/res_company.py
  account_reconciliation_widget_limit_aml/models/res_config_settings.py
  account_reconciliation_widget_limit_aml/readme/CONTRIBUTORS.rst
  account_reconciliation_widget_limit_aml/readme/DESCRIPTION.rst
  account_reconciliation_widget_limit_aml/readme/USAGE.rst
  account_reconciliation_widget_limit_aml/static/description/icon.png
  account_reconciliation_widget_limit_aml/static/description/index.html
  account_reconciliation_widget_limit_aml/views/res_config_settings_views.xml
  setup/account_reconciliation_widget_limit_aml/odoo/addons/account_reconciliation_widget_limit_aml
  setup/account_reconciliation_widget_limit_aml/setup.py
Labels: approved, bot is merging ⏳
