Repository OCA/account-reconcile, pull requests merged in 2023-03, with the labels that each got.

#533 [16.0] account_statement_base: change licence AGPL -> LGPL
  account_statement_base/__manifest__.py
Labels: bot is merging ⏳

#534 [16.0] account_statement_base: add development_status in manifest
  account_statement_base/__manifest__.py
Labels: bot is merging ⏳

#532 [16.0][ADD] module account_move_line_reconcile_manual
  account_move_line_reconcile_manual/README.rst
  account_move_line_reconcile_manual/__init__.py
  account_move_line_reconcile_manual/__manifest__.py
  account_move_line_reconcile_manual/readme/CONTRIBUTORS.rst
  account_move_line_reconcile_manual/readme/DESCRIPTION.rst
  account_move_line_reconcile_manual/security/ir.model.access.csv
  account_move_line_reconcile_manual/static/description/sshot_full_rec.png
  account_move_line_reconcile_manual/static/description/sshot_partial_rec.png
  account_move_line_reconcile_manual/static/description/sshot_rec_writeoff.png
  account_move_line_reconcile_manual/tests/__init__.py
  account_move_line_reconcile_manual/tests/test_reconcile_manual.py
  account_move_line_reconcile_manual/views/account_move_line.xml
  account_move_line_reconcile_manual/wizards/__init__.py
  account_move_line_reconcile_manual/wizards/account_move_line_reconcile_manual.py
  account_move_line_reconcile_manual/wizards/account_move_line_reconcile_manual_view.xml
  setup/account_move_line_reconcile_manual/odoo/addons/account_move_line_reconcile_manual
  setup/account_move_line_reconcile_manual/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#500 [ADD] account_reconcile_oca
  account_reconcile_oca/README.rst
  account_reconcile_oca/__init__.py
  account_reconcile_oca/__manifest__.py
  account_reconcile_oca/demo/demo.xml
  account_reconcile_oca/hooks.py
  account_reconcile_oca/models/__init__.py
  account_reconcile_oca/models/account_account_reconcile.py
  account_reconcile_oca/models/account_bank_statement_line.py
  account_reconcile_oca/models/account_journal.py
  account_reconcile_oca/models/account_reconcile_abstract.py
  account_reconcile_oca/readme/CONTRIBUTORS.rst
  account_reconcile_oca/readme/DESCRIPTION.rst
  account_reconcile_oca/readme/ROADMAP.rst
  account_reconcile_oca/readme/USAGE.rst
  account_reconcile_oca/security/ir.model.access.csv
  account_reconcile_oca/static/description/icon.png
  account_reconcile_oca/static/description/index.html
  account_reconcile_oca/static/src/js/reconcile/reconcile_controller.esm.js
  account_reconcile_oca/static/src/js/reconcile/reconcile_kanban_record.esm.js
  account_reconcile_oca/static/src/js/reconcile/reconcile_renderer.esm.js
  account_reconcile_oca/static/src/js/reconcile/reconcile_view.esm.js
  account_reconcile_oca/static/src/js/reconcile_form/reconcile_form_controller.esm.js
  account_reconcile_oca/static/src/js/reconcile_form/reconcile_form_notebook.esm.js
  account_reconcile_oca/static/src/js/reconcile_form/reconcile_form_renderer.esm.js
  account_reconcile_oca/static/src/js/reconcile_form/reconcile_form_view.esm.js
  account_reconcile_oca/static/src/js/reconcile_manual/reconcile_manual_controller.esm.js
  account_reconcile_oca/static/src/js/reconcile_manual/reconcile_manual_view.esm.js
  account_reconcile_oca/static/src/js/reconcile_move_line/reconcile_move_line_controller.esm.js
  account_reconcile_oca/static/src/js/reconcile_move_line/reconcile_move_line_renderer.esm.js
  account_reconcile_oca/static/src/js/reconcile_move_line/reconcile_move_line_view.esm.js
  account_reconcile_oca/static/src/js/widgets/reconcile_chatter_field.esm.js
  account_reconcile_oca/static/src/js/widgets/reconcile_data_widget.esm.js
  account_reconcile_oca/static/src/js/widgets/reconcile_move_line_widget.esm.js
  account_reconcile_oca/static/src/js/widgets/selection_badge_uncheck.esm.js
  account_reconcile_oca/static/src/scss/reconcile.scss
  account_reconcile_oca/static/src/xml/reconcile.xml
  account_reconcile_oca/tests/__init__.py
  account_reconcile_oca/tests/test_account_reconcile.py
  account_reconcile_oca/tests/test_bank_account_reconcile.py
  account_reconcile_oca/views/account_account.xml
  account_reconcile_oca/views/account_account_reconcile.xml
  account_reconcile_oca/views/account_bank_statement_line.xml
  account_reconcile_oca/views/account_journal.xml
  account_reconcile_oca/views/account_move.xml
  account_reconcile_oca/views/account_move_line.xml
  account_statement_base/views/account_bank_statement_line.xml
  setup/account_reconcile_oca/odoo/addons/account_reconcile_oca
  setup/account_reconcile_oca/setup.py
Labels: needs review, bot is merging ⏳
