Repository OCA/account-reconcile, pull requests merged in 2024-05, with the labels that each got.

#654 [17.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .ruff.toml
  account_mass_reconcile/models/base_advanced_reconciliation.py
  account_reconcile_model_oca/models/account_bank_statement_line.py
  account_reconcile_model_oca/models/account_reconcile_model.py
  account_reconcile_model_oca/tests/common.py
  account_reconcile_model_oca/tests/test_reconciliation_match.py
  account_reconcile_oca/models/account_bank_statement_line.py
  account_reconcile_oca/tests/test_bank_account_reconcile.py
Labels: help wanted, needs review, bot is merging ⏳

#657 [15.0][FIX] account_reconciliation_widget: Error when click reconcile button
  account_reconciliation_widget/models/reconciliation_widget.py
Labels: bot is merging ⏳

#653 [17.0][FIX] account_reconcile_oca: use the right parameters on views
  account_reconcile_oca/views/account_account_reconcile.xml
Labels: approved, bot is merging ⏳

#658 [16.0][FIX] account_reconcile_oca: Replace invoice_due_date for date_maturity field on reconcile view.
  account_reconcile_oca/models/account_move_line.py
  account_reconcile_oca/views/account_move_line.xml
Labels: approved, ready to merge, bot is merging ⏳

#661 [17.0][FIX] account_reconcile_oca: Replace invoice_due_date for date_maturity field on reconcile view.
  account_reconcile_oca/models/account_move_line.py
  account_reconcile_oca/views/account_move_line.xml
Labels: approved, bot is merging ⏳
