Repository OCA/account-reconcile, pull requests merged in 2024-12, with the labels that each got.

#759 [16.0][FIX] account_statement_base: statement end balance compute new lines
  account_statement_base/models/account_bank_statement.py
Labels: approved, ready to merge, bot is merging ⏳

#677 [17.0][IMP] account_reconcile_oca: Use receivable/payable account on statements with partner as suspense account
  account_reconcile_oca/models/account_bank_statement_line.py
  account_reconcile_oca/tests/test_bank_account_reconcile.py
Labels: bot is merging ⏳, stale

#762 [16.0][IMP] account_reconcile_oca: Add auto-reconcile compatibility (Example: Rule to match invoices/bills)
  account_reconcile_oca/models/account_bank_statement_line.py
  account_reconcile_oca/tests/test_bank_account_reconcile.py
Labels: approved, bot is merging ⏳

#686 [16.0][FIX] account_mass_reconcile: New environment is initialized when ...
  account_mass_reconcile/models/mass_reconcile.py
Labels: approved, bot is merging ⏳

#763 [16.0][IMP] account_reconcile: ux improvements
  account_reconcile_oca/models/account_journal.py
  account_reconcile_oca/views/account_bank_statement_line.xml
  account_statement_base/views/account_bank_statement_line.xml
Labels: bot is merging ⏳

#766 [16.0][FIX] account_reconcile_analytic_tag: Avoid error when accessing the reconciliation view
  account_reconcile_analytic_tag/models/account_reconcile_model.py
Labels: approved, bot is merging ⏳

#765 [17.0][FIX] account_reconcile_oca: Fixed analytic distribution update
  account_reconcile_oca/models/account_bank_statement_line.py
Labels: approved, bot is merging ⏳

#769 [16.0][FIX] account_reconcile_oca: Fixed analytic distribution update
  account_reconcile_oca/models/account_bank_statement_line.py
Labels: bot is merging ⏳

#770 [18.0][IMP] account_statement_base: Add group by date
  account_statement_base/views/account_bank_statement_line.xml
Labels: bot is merging ⏳

#767 [17.0][FIX] account_reconcile_oca: Fix selection_badge_uncheck to correctly apply the corresponding domain
  account_reconcile_oca/static/src/js/widgets/selection_badge_uncheck.esm.js
Labels: approved, bot is merging ⏳

#720 [16.0] [IMP] account_reconcile_oca: pass default name for lines created through reconciliation models
  account_reconcile_oca/models/account_bank_statement_line.py
Labels: approved, bot is merging ⏳
