Repository OCA/account-reconcile, pull requests merged in 2024-11, with the labels that each got.

#743 [IMP] account_statement_base: no need to depend on account_reconcile_model_oca tests
  account_statement_base/tests/test_account_statement_base.py
Labels: bot is merging ⏳

#744 [16][FIX] account_reconcile_oca : keep aml label when empty on manual write-off reconcile model
  account_reconcile_oca/models/account_bank_statement_line.py
Labels: approved, bot is merging ⏳

#746 [17][FIX] account_reconcile_oca : keep aml label when empty on manual write-off reconcile model
  account_reconcile_oca/models/account_bank_statement_line.py
Labels: bot is merging ⏳

#747 [16][FIX] account_reconcile_oca : keep partner line case of manual button reconcile
  account_reconcile_oca/models/account_bank_statement_line.py
Labels: bot is merging ⏳

#748 [17][FIX] account_reconcile_oca : keep partner line case of manual button reconcile
  account_reconcile_oca/models/account_bank_statement_line.py
Labels: bot is merging ⏳

#749 [16.0][FIX] account_statement_base: Add default_statement_id to the context to create the statement lines linked to it
  account_statement_base/models/account_bank_statement.py
Labels: bot is merging ⏳

#751 [17.0][FIX] account_statement_base: Add default_statement_id to the context to create the statement lines linked to it
  account_statement_base/models/account_bank_statement.py
  account_statement_base/views/account_bank_statement_line.xml
Labels: approved, bot is merging ⏳

#745 [16.0][FIX] account_statement_base: Allow statements to be created by clicking on the New button.
  account_statement_base/views/account_bank_statement.xml
Labels: approved, bot is merging ⏳

#752 [17.0][FIX] account_statement_base: Allow statements to be created by clicking on the New button.
  account_statement_base/views/account_bank_statement.xml
Labels: bot is merging ⏳

#739 [18.0][MIG] account_statement_base: Migration to 18.0
  account_statement_base/README.rst
  account_statement_base/__init__.py
  account_statement_base/__manifest__.py
  account_statement_base/i18n/account_statement_base.pot
  account_statement_base/i18n/es.po
  account_statement_base/i18n/fr.po
  account_statement_base/i18n/it.po
  account_statement_base/i18n/pt_BR.po
  account_statement_base/i18n/zh.po
  account_statement_base/i18n/zh_CN.po
  account_statement_base/models/__init__.py
  account_statement_base/models/account_bank_statement.py
  account_statement_base/models/account_bank_statement_line.py
  account_statement_base/models/account_journal_dashboard.py
  account_statement_base/pyproject.toml
  account_statement_base/readme/CONTRIBUTORS.md
  account_statement_base/readme/CREDITS.md
  account_statement_base/readme/DESCRIPTION.md
  account_statement_base/static/description/icon.png
  account_statement_base/static/description/index.html
  account_statement_base/tests/__init__.py
  account_statement_base/tests/test_account_statement_base.py
  account_statement_base/views/account_bank_statement.xml
  account_statement_base/views/account_bank_statement_line.xml
Labels: approved, ready to merge, bot is merging ⏳

#756 [18.0][IMP] account_statement_base: Remove unnecessary code
  account_statement_base/models/account_bank_statement.py
  account_statement_base/models/account_bank_statement_line.py
Labels: bot is merging ⏳

#757 [16.0][IMP] account_reconcile_oca: reconcile lines from statement
  account_reconcile_oca/models/account_bank_statement.py
  account_reconcile_oca/views/account_bank_statement.xml
Labels: approved, bot is merging ⏳

#758 [16.0][ADD] account_reconcile_analytic_tag: New module
  account_reconcile_analytic_tag/README.rst
  account_reconcile_analytic_tag/__init__.py
  account_reconcile_analytic_tag/__manifest__.py
  account_reconcile_analytic_tag/i18n/account_reconcile_analytic_tag.pot
  account_reconcile_analytic_tag/i18n/es.po
  account_reconcile_analytic_tag/models/__init__.py
  account_reconcile_analytic_tag/models/account_bank_statement_line.py
  account_reconcile_analytic_tag/models/account_reconcile_abstract.py
  account_reconcile_analytic_tag/readme/CONTRIBUTORS.rst
  account_reconcile_analytic_tag/readme/DESCRIPTION.rst
  account_reconcile_analytic_tag/static/description/icon.png
  account_reconcile_analytic_tag/static/description/index.html
  account_reconcile_analytic_tag/tests/__init__.py
  account_reconcile_analytic_tag/tests/test_account_reconcile_analytic_tag.py
  account_reconcile_analytic_tag/views/account_bank_statement_line_views.xml
  account_reconcile_oca/models/account_bank_statement_line.py
  setup/account_reconcile_analytic_tag/odoo/addons/account_reconcile_analytic_tag
  setup/account_reconcile_analytic_tag/setup.py
Labels: approved, bot is merging ⏳

#761 [16.0][IMP] account_reconcile_analytic_tag: Add analytic tags to reconciliation model lines
  account_reconcile_analytic_tag/__manifest__.py
  account_reconcile_analytic_tag/models/__init__.py
  account_reconcile_analytic_tag/models/account_reconcile_model.py
  account_reconcile_analytic_tag/static/description/index.html
  account_reconcile_analytic_tag/views/account_bank_statement_line_views.xml
  account_reconcile_analytic_tag/views/account_reconcile_model_views.xml
Labels: bot is merging ⏳
