Repository OCA/account-reconcile, pull requests merged in 2024-06, with the labels that each got.

#662 [16.0][IMP] account_reconcile_oca: Several improvements
  account_reconcile_oca/__manifest__.py
  account_reconcile_oca/models/__init__.py
  account_reconcile_oca/models/account_bank_statement.py
  account_reconcile_oca/models/account_bank_statement_line.py
  account_reconcile_oca/models/account_journal.py
  account_reconcile_oca/models/res_company.py
  account_reconcile_oca/models/res_config_settings.py
  account_reconcile_oca/static/src/js/reconcile/reconcile_controller.esm.js
  account_reconcile_oca/static/src/js/reconcile/reconcile_renderer.esm.js
  account_reconcile_oca/static/src/js/reconcile_form/reconcile_form_controller.esm.js
  account_reconcile_oca/static/src/js/widgets/reconcile_data_widget.esm.js
  account_reconcile_oca/static/src/scss/reconcile.scss
  account_reconcile_oca/static/src/xml/reconcile.xml
  account_reconcile_oca/views/account_bank_statement.xml
  account_reconcile_oca/views/account_bank_statement_line.xml
  account_reconcile_oca/views/account_journal.xml
  account_reconcile_oca/views/res_config_settings.xml
Labels: approved, ready to merge, bot is merging ⏳

#663 [16.0][IMP] account_statement_base: Add statement form view
  account_statement_base/README.rst
  account_statement_base/__manifest__.py
  account_statement_base/readme/CONTRIBUTORS.rst
  account_statement_base/readme/DESCRIPTION.rst
  account_statement_base/static/description/index.html
  account_statement_base/views/account_bank_statement.xml
  account_statement_base/views/account_bank_statement_line.xml
Labels: approved, ready to merge, bot is merging ⏳

#671 [16.0][IMP] account_reconcile_oca: Add fields to account.account.reconcile search view
  account_reconcile_oca/views/account_account_reconcile.xml
Labels: approved, bot is merging ⏳

#672 [17.0][IMP] account_reconcile_oca: Add fields to account.account.reconcile search view
  account_reconcile_oca/views/account_account_reconcile.xml
Labels: bot is merging ⏳
