Repository OCA/account-reconcile, pull requests merged in 2024-03, with the labels that each got.

#636 [FIX] account_reconcile_oca: Fix foreign currency
  account_reconcile_oca/models/account_bank_statement_line.py
Labels: bot is merging ⏳

#637 [16.0][IMP] [account_statement_base account_reconcile_oca] make statements listed and editable
  account_reconcile_oca/views/account_bank_statement_line.xml
  account_statement_base/views/account_bank_statement_line.xml
Labels: approved, ready to merge, bot is merging ⏳

#640 [16.0][FIX] account_reconcile_oca: Use counterparts properly
  account_reconcile_oca/models/account_bank_statement_line.py
  account_reconcile_oca/models/account_reconcile_abstract.py
Labels: approved, bot is merging ⏳

#641 [16.0][FIX] account_reconcile_oca: Don't show partner label if none
  account_reconcile_oca/static/src/xml/reconcile.xml
Labels: bot is merging ⏳
