Repository OCA/account-reconcile, pull requests merged in 2024-08, with the labels that each got.

#679 [16.0][IMP] account_statement_base: Show action to create Statements
  account_statement_base/__init__.py
  account_statement_base/models/__init__.py
  account_statement_base/models/account_journal_dashboard.py
Labels: approved, bot is merging ⏳

#681 [ADD] account_in_payment
  account_in_payment/README.rst
  account_in_payment/__init__.py
  account_in_payment/__manifest__.py
  account_in_payment/models/__init__.py
  account_in_payment/models/account_move.py
  account_in_payment/readme/CONTRIBUTORS.md
  account_in_payment/readme/DESCRIPTION.md
  account_in_payment/static/description/icon.png
  account_in_payment/static/description/index.html
  account_in_payment/tests/__init__.py
  account_in_payment/tests/test_bank_account_reconcile.py
  setup/account_in_payment/odoo/addons/account_in_payment
  setup/account_in_payment/setup.py
Labels: approved, bot is merging ⏳

#682 [16.0][IMP+FIX] account_reconcile_oca + account_statement_base
  account_reconcile_oca/static/src/js/reconcile/reconcile_controller.esm.js
  account_reconcile_oca/static/src/js/reconcile_form/reconcile_form_controller.esm.js
  account_reconcile_oca/views/account_move.xml
  account_reconcile_oca/views/account_move_line.xml
  account_statement_base/views/account_bank_statement_line.xml
Labels: bot is merging ⏳

#646 [14.0][IMP] account_reconciliation_widget: Performance opening reconciliation widget
  account_mass_reconcile_as_job/tests/test_scenario_reconcile_as_job.py
  account_reconciliation_widget/models/reconciliation_widget.py
Labels: approved, bot is merging ⏳, stale
