Repository OCA/account-reconcile, pull requests merged in 2024-02, with the labels that each got.

#626 [16.0][FIX] account_reconcile_oca: improve error messages and allow to reconcile with different partners
  account_reconcile_oca/models/account_account_reconcile.py
  account_reconcile_oca/models/account_move_line.py
Labels: approved, bot is merging ⏳

#614 [17.0][MIG] account_statement_base: Migration to 17.0
  account_statement_base/README.rst
  account_statement_base/__init__.py
  account_statement_base/__manifest__.py
  account_statement_base/i18n/account_statement_base.pot
  account_statement_base/i18n/es.po
  account_statement_base/i18n/fr.po
  account_statement_base/i18n/pt_BR.po
  account_statement_base/pyproject.toml
  account_statement_base/readme/CONTRIBUTORS.md
  account_statement_base/readme/DESCRIPTION.md
  account_statement_base/static/description/icon.png
  account_statement_base/static/description/index.html
  account_statement_base/views/account_bank_statement.xml
  account_statement_base/views/account_bank_statement_line.xml
Labels: approved, ready to merge, bot is merging ⏳

#627 [16.0][IMP] account_reconcile_oca: add due date field in account_move_line tree view
  account_reconcile_oca/models/account_move_line.py
  account_reconcile_oca/views/account_move_line.xml
Labels: approved, ready to merge, bot is merging ⏳

#633 [15.0][FIX] account_reconciliation_widget: Avoid unbalanced foreign currency reconciliations + exclude own amls in reconcile models propositions
  account_reconciliation_widget/models/account_bank_statement.py
  account_reconciliation_widget/models/reconciliation_widget.py
Labels: bot is merging ⏳
