Repository OCA/account-reconcile, pull requests merged in 2024-09, with the labels that each got.

#668 [IMP] account_reconcile_oca: Fix multicurrency journal management
  account_reconcile_oca/models/account_account_reconcile.py
  account_reconcile_oca/models/account_bank_statement_line.py
  account_reconcile_oca/models/account_reconcile_abstract.py
  account_reconcile_oca/static/src/js/widgets/reconcile_data_widget.esm.js
  account_reconcile_oca/tests/test_bank_account_reconcile.py
  account_reconcile_oca/views/account_bank_statement_line.xml
Labels: approved, ready to merge, bot is merging ⏳

#688 [14.0][MIG] account in payment: Migration to 14.0
  account_in_payment/README.rst
  account_in_payment/__init__.py
  account_in_payment/__manifest__.py
  account_in_payment/i18n/account_in_payment.pot
  account_in_payment/i18n/it.po
  account_in_payment/i18n/pt.po
  account_in_payment/models/__init__.py
  account_in_payment/models/account_move.py
  account_in_payment/readme/CONTRIBUTORS.md
  account_in_payment/readme/DESCRIPTION.md
  account_in_payment/static/description/icon.png
  account_in_payment/static/description/index.html
  account_in_payment/tests/__init__.py
  account_in_payment/tests/test_bank_account_reconcile.py
  setup/account_in_payment/odoo/addons/account_in_payment
  setup/account_in_payment/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#683 [17.0][IMP] account_statement_base + account_reconcile: Forward port missing commits
  account_reconcile_oca/models/account_bank_statement_line.py
  account_reconcile_oca/static/src/js/reconcile/reconcile_controller.esm.js
  account_reconcile_oca/static/src/js/reconcile_form/reconcile_form_controller.esm.js
  account_reconcile_oca/static/src/js/widgets/reconcile_chatter_field.esm.js
  account_reconcile_oca/views/account_move.xml
  account_reconcile_oca/views/account_move_line.xml
  account_statement_base/README.rst
  account_statement_base/__init__.py
  account_statement_base/__manifest__.py
  account_statement_base/models/__init__.py
  account_statement_base/models/account_journal_dashboard.py
  account_statement_base/readme/CONTRIBUTORS.md
  account_statement_base/static/description/index.html
  account_statement_base/views/account_bank_statement.xml
  account_statement_base/views/account_bank_statement_line.xml
Labels: bot is merging ⏳

#690 [16.0][FIX] account_reconcile_oca: Fix wrong display on reconciled moves
  account_reconcile_oca/models/account_bank_statement_line.py
  account_reconcile_oca/tests/test_bank_account_reconcile.py
Labels: bot is merging ⏳

#684 [IMP] account_reconcile_oca: Split overflow
  account_reconcile_oca/static/src/scss/reconcile.scss
Labels: bot is merging ⏳

#699 [16.0][IMP] account_reconcile_oca: Only fix partner on payment accounts
  account_reconcile_oca/models/account_account_reconcile.py
Labels: bot is merging ⏳

#704 [17.0][IMP] account_reconcile_oca: Only fix partner on payment accounts
  account_reconcile_oca/models/account_account_reconcile.py
Labels: bot is merging ⏳

#703 [16.0][FIX] account_reconcile_oca: Don't apply max_amount on intermediate counterparts
  account_reconcile_oca/models/account_account_reconcile.py
Labels: bot is merging ⏳

#705 [17.0][FIX] account_reconcile_oca: Don't apply max_amount on intermediate counterparts
  account_reconcile_oca/models/account_account_reconcile.py
Labels: bot is merging ⏳

#702 [16.0] fix odoo trace at install or update *account_reconcile_oca* module
  account_reconcile_oca/models/account_bank_statement_line.py
Labels: approved, bot is merging ⏳

#678 [16.0][IMP] account_statement_base: add possibility to navigate from statement lines to the associated journal entry
  account_statement_base/README.rst
  account_statement_base/models/__init__.py
  account_statement_base/models/account_bank_statement_line.py
  account_statement_base/readme/CONTRIBUTORS.rst
  account_statement_base/static/description/index.html
  account_statement_base/views/account_bank_statement_line.xml
Labels: approved, bot is merging ⏳

#707 [16.0][FIX] account_statement_base: Allow to create new manual transactions in tree view
  account_statement_base/views/account_bank_statement_line.xml
Labels: approved, bot is merging ⏳

#706 [16.0][IMP] make the statements views editable=top by default
  account_statement_base/models/__init__.py
  account_statement_base/models/account_bank_statement.py
  account_statement_base/views/account_bank_statement.xml
Labels: bot is merging ⏳

#708 [17.0][FIX] account_statement_base: Allow to create new manual transactions in tree view
  account_statement_base/README.rst
  account_statement_base/models/__init__.py
  account_statement_base/models/account_bank_statement_line.py
  account_statement_base/readme/CONTRIBUTORS.md
  account_statement_base/static/description/index.html
  account_statement_base/views/account_bank_statement_line.xml
Labels: approved, bot is merging ⏳

#659 [16.0][IMP] account_statement_base: link to account move lines from statements
  account_statement_base/models/account_bank_statement.py
  account_statement_base/models/account_bank_statement_line.py
  account_statement_base/tests/__init__.py
  account_statement_base/tests/test_account_statement_base.py
  account_statement_base/views/account_bank_statement.xml
Labels: approved, bot is merging ⏳

#713 [17.0][IMP] account_statement_base: add smart button on view_bank_statement_form linking to journal items
  account_statement_base/models/__init__.py
  account_statement_base/models/account_bank_statement.py
  account_statement_base/tests/__init__.py
  account_statement_base/tests/test_account_statement_base.py
  account_statement_base/views/account_bank_statement.xml
Labels: bot is merging ⏳
