Repository OCA/account-reconcile, pull requests merged in 2025-04, with the labels that each got.

#818 [16.0][IMP] account_reconcile_oca: Allow an option to avoid a function
  account_reconcile_oca/models/account_bank_statement_line.py
Labels: approved, bot is merging ⏳

#819 [18.0][FIX] account_reconcile_model_oca: FWPs from account
  account_reconcile_model_oca/models/account_bank_statement_line.py
  account_reconcile_model_oca/models/account_reconcile_model.py
  account_reconcile_model_oca/tests/test_reconciliation_match.py
Labels: bot is merging ⏳

#820 [17.0][IMP] account_reconcile_oca: Allow an option to avoid a function
  account_reconcile_oca/models/account_bank_statement_line.py
Labels: approved, bot is merging ⏳

#822 [16.0][FIX] account_reconcile_oca: make a domain consider company
  account_reconcile_oca/models/account_bank_statement_line.py
Labels: approved, bot is merging ⏳

#825 [FIX] account_reconcile_oca: Apply matching of partners on reconciliation models
  account_reconcile_oca/models/account_bank_statement_line.py
Labels: bot is merging ⏳

#826 [17.0][FIX] account_reconcile_oca: Apply matching of partners on reconciliation models
  account_reconcile_oca/models/account_bank_statement_line.py
Labels: bot is merging ⏳

#827 [18.0][FIX] account_reconcile_oca: Apply matching of partners on reconciliation models
  account_reconcile_oca/models/account_bank_statement_line.py
Labels: bot is merging ⏳

#829 [18.0][FIX] account_reconcile_oca
  account_reconcile_oca/__manifest__.py
  account_reconcile_oca/static/src/js/reconcile_manual/reconcile_manual_controller.esm.js
  account_reconcile_oca/static/src/js/reconcile_manual/reconcile_manual_view.esm.js
  account_reconcile_oca/static/src/js/reconcile_move_line/reconcile_move_line_controller.esm.js
  account_reconcile_oca/views/account_account_reconcile.xml
Labels: bot is merging ⏳

#832 [17.0][FIX] account_reconcile_oca: Replace name_get() to delete the warning log
  account_reconcile_oca/models/account_bank_statement_line.py
Labels: approved, bot is merging ⏳

#838 [17.0][IMP] account_reconcile_oca: Define a unique partner name to avoid conflicts
  account_reconcile_oca/tests/test_bank_account_reconcile.py
Labels: approved
