Repository OCA/account-reconcile, pull requests merged in 2025-02, with the labels that each got.

#792 [16.0][FIX] account_reconcile_oca: Fix currency and amount when using reconciliation models
  account_reconcile_oca/models/account_bank_statement_line.py
  account_reconcile_oca/tests/test_bank_account_reconcile.py
Labels: approved, bot is merging ⏳

#777 [16.0][FIX] account_reconcile_oca: KeyError on data
  account_reconcile_oca/models/account_bank_statement_line.py
Labels: approved, bot is merging ⏳

#795 [17.0][FIX] account_reconcile_oca: KeyError on data
  account_reconcile_oca/models/account_bank_statement_line.py
Labels: bot is merging ⏳

#784 [16][account_reconcile_oca] FIX amounts inconsistencies between statement line reconcile_data and accounting entries
  account_reconcile_oca/models/account_bank_statement_line.py
  account_reconcile_oca/tests/test_bank_account_reconcile.py
Labels: approved, bot is merging ⏳

#788 [17] account_reconcile_oca : Forward port multi currency management from 16
  account_reconcile_oca/models/account_account_reconcile.py
  account_reconcile_oca/models/account_bank_statement_line.py
  account_reconcile_oca/models/account_reconcile_abstract.py
  account_reconcile_oca/static/src/js/widgets/reconcile_data_widget.esm.js
  account_reconcile_oca/static/src/xml/reconcile.xml
  account_reconcile_oca/tests/test_bank_account_reconcile.py
Labels: approved, bot is merging ⏳

#798 [16.0][IMP] account_reconcile_oca: Allow to select all lines at once
  account_reconcile_oca/models/account_account_reconcile.py
  account_reconcile_oca/models/account_bank_statement_line.py
  account_reconcile_oca/models/account_reconcile_abstract.py
  account_reconcile_oca/static/src/js/reconcile_move_line/reconcile_move_line_controller.esm.js
  account_reconcile_oca/static/src/js/reconcile_move_line/reconcile_move_line_view.esm.js
  account_reconcile_oca/static/src/js/widgets/reconcile_move_line_widget.esm.js
  account_reconcile_oca/static/src/xml/reconcile.xml
Labels: bot is merging ⏳

#799 [17.0][IMP] account_reconcile_oca: Allow to select all lines at once
  account_reconcile_oca/i18n/account_reconcile_oca.pot
  account_reconcile_oca/i18n/es.po
  account_reconcile_oca/models/account_account_reconcile.py
  account_reconcile_oca/models/account_bank_statement_line.py
  account_reconcile_oca/models/account_reconcile_abstract.py
  account_reconcile_oca/static/src/js/reconcile_move_line/reconcile_move_line_controller.esm.js
  account_reconcile_oca/static/src/js/reconcile_move_line/reconcile_move_line_view.esm.js
  account_reconcile_oca/static/src/js/widgets/reconcile_move_line_widget.esm.js
  account_reconcile_oca/static/src/xml/reconcile.xml
Labels: bot is merging ⏳

#791 [16.0][MIG] account_partner_reconcile
  account_partner_reconcile/README.rst
  account_partner_reconcile/__init__.py
  account_partner_reconcile/__manifest__.py
  account_partner_reconcile/i18n/account_partner_reconcile.pot
  account_partner_reconcile/i18n/da.po
  account_partner_reconcile/i18n/es.po
  account_partner_reconcile/i18n/es_AR.po
  account_partner_reconcile/i18n/fr.po
  account_partner_reconcile/i18n/fr_FR.po
  account_partner_reconcile/i18n/pt.po
  account_partner_reconcile/models/__init__.py
  account_partner_reconcile/models/res_partner.py
  account_partner_reconcile/readme/CONFIGURE.rst
  account_partner_reconcile/readme/CONTRIBUTORS.rst
  account_partner_reconcile/readme/DESCRIPTION.rst
  account_partner_reconcile/readme/USAGE.rst
  account_partner_reconcile/static/description/icon.png
  account_partner_reconcile/static/description/index.html
  account_partner_reconcile/tests/__init__.py
  account_partner_reconcile/tests/test_account_partner_reconcile.py
  account_partner_reconcile/views/res_partner_view.xml
  setup/account_partner_reconcile/odoo/addons/account_partner_reconcile
  setup/account_partner_reconcile/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#794 [16.0][IMP] account_reconcile_oca: improve visibility of partner on bank statement line
  account_reconcile_oca/views/account_bank_statement_line.xml
Labels: approved, ready to merge, bot is merging ⏳

#804 [17.0][FIX] account_reconcile_oca: Replace name_get() to delete the warning log
  account_reconcile_oca/models/account_bank_statement_line.py
Labels: bot is merging ⏳

#807 [16.0][FIX] account_reconcile_oca: Avoiding the singleton error related to _get_reconcile_line()
  account_reconcile_oca/models/account_bank_statement_line.py
Labels: approved, bot is merging ⏳

#738 [18.0][MIG] account_reconcile_model_oca: Migration to 18.0
  account_reconcile_model_oca/README.rst
  account_reconcile_model_oca/__init__.py
  account_reconcile_model_oca/__manifest__.py
  account_reconcile_model_oca/i18n/account_reconcile_model_oca.pot
  account_reconcile_model_oca/i18n/it.po
  account_reconcile_model_oca/i18n/zh_CN.po
  account_reconcile_model_oca/models/__init__.py
  account_reconcile_model_oca/models/account_bank_statement_line.py
  account_reconcile_model_oca/models/account_reconcile_model.py
  account_reconcile_model_oca/pyproject.toml
  account_reconcile_model_oca/readme/CONTRIBUTORS.md
  account_reconcile_model_oca/readme/CREDITS.md
  account_reconcile_model_oca/readme/DESCRIPTION.md
  account_reconcile_model_oca/static/description/icon.png
  account_reconcile_model_oca/static/description/index.html
  account_reconcile_model_oca/tests/__init__.py
  account_reconcile_model_oca/tests/common.py
  account_reconcile_model_oca/tests/test_reconciliation_match.py
Labels: approved, ready to merge, bot is merging ⏳

#809 [17.0][FIX] account_reconcile_oca: Avoiding the singleton error related to _get_reconcile_line()
  account_reconcile_oca/models/account_bank_statement_line.py
Labels: approved, bot is merging ⏳
