Repository OCA/account-reconcile, pull requests merged in 2025-07, with the labels that each got.

#771 [16.0][MIG] account_move_reconcile_helper: Migration to 16.0
  account_move_reconcile_helper/README.rst
  account_move_reconcile_helper/__init__.py
  account_move_reconcile_helper/__manifest__.py
  account_move_reconcile_helper/i18n/account_move_reconcile_helper.pot
  account_move_reconcile_helper/i18n/es.po
  account_move_reconcile_helper/i18n/fr.po
  account_move_reconcile_helper/i18n/hr.po
  account_move_reconcile_helper/models/__init__.py
  account_move_reconcile_helper/models/account_move_line.py
  account_move_reconcile_helper/readme/CONTRIBUTORS.rst
  account_move_reconcile_helper/readme/DESCRIPTION.rst
  account_move_reconcile_helper/static/description/icon.png
  account_move_reconcile_helper/static/description/index.html
  account_move_reconcile_helper/tests/__init__.py
  account_move_reconcile_helper/tests/test_account_move_reconcile_helper.py
  account_move_reconcile_helper/views/account_move_line.xml
  setup/account_move_reconcile_helper/odoo/addons/account_move_reconcile_helper
  setup/account_move_reconcile_helper/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#873 [17.0][IMP] account_statement_base: Add statement_id field to statement lines tree view
  account_statement_base/views/account_bank_statement_line.xml
Labels: approved, ready to merge, bot is merging ⏳

#870 [17.0][FIX] account_reconcile_oca: Correct filtering in the manual_model_id field by the appropriate allowed journals
  account_reconcile_oca/models/account_bank_statement_line.py
Labels: approved, bot is merging ⏳

#877 [18.0][IMP] account_statement_base: Add statement_id field to statement lines tree view
  account_statement_base/views/account_bank_statement_line.xml
Labels: bot is merging ⏳

#884 [16.0][IMP] account_reconcile_oca: Fix update of external currency
  account_reconcile_oca/models/account_bank_statement_line.py
  account_reconcile_oca/views/account_bank_statement_line.xml
Labels: approved

#888 [18.0] [IMP] account_reconcile_oca: Fix update of external currency
  account_reconcile_oca/models/account_bank_statement_line.py
  account_reconcile_oca/views/account_bank_statement_line.xml
Labels: approved, bot is merging ⏳

#890 [16.0][IMP] account_reconcile_oca: Fix the amount in currency once we reconcile. Add tests
  account_reconcile_oca/models/account_bank_statement_line.py
  account_reconcile_oca/models/account_reconcile_abstract.py
  account_reconcile_oca/tests/test_bank_account_reconcile.py
Labels: approved, bot is merging ⏳

#892 [18.0][IMP] account_reconcile_oca: Fix the amount in currency once we reconcile. Add tests
  account_reconcile_oca/models/account_bank_statement_line.py
  account_reconcile_oca/models/account_reconcile_abstract.py
  account_reconcile_oca/tests/test_bank_account_reconcile.py
Labels: approved, bot is merging ⏳

#893 [16.0][FIX] account_reconcile_oca: Don't use residual on already reconciled lines
  account_reconcile_oca/README.rst
  account_reconcile_oca/models/account_bank_statement_line.py
  account_reconcile_oca/models/account_reconcile_abstract.py
  account_reconcile_oca/readme/CREDITS.rst
  account_reconcile_oca/static/description/index.html
  account_reconcile_oca/tests/test_bank_account_reconcile.py
Labels: approved, bot is merging ⏳

#895 [18.0][FIX] account_reconcile_oca: Don't use residual on already reconciled lines
  account_reconcile_oca/README.rst
  account_reconcile_oca/models/account_bank_statement_line.py
  account_reconcile_oca/models/account_reconcile_abstract.py
  account_reconcile_oca/readme/CREDITS.md
  account_reconcile_oca/static/description/index.html
  account_reconcile_oca/tests/test_bank_account_reconcile.py
Labels: approved, bot is merging ⏳

#898 [18.0][FIX] account_reconcile_oca: Correct open action for Journal Items
  account_reconcile_oca/models/account_journal.py
Labels: approved, bot is merging ⏳

#897 [17.0][FIX] account_reconcile_oca: Correct open action for Journal Items
  account_reconcile_oca/models/account_journal.py
Labels: approved, bot is merging ⏳
