Repository OCA/account-reconcile, pull requests merged in 2025-01, with the labels that each got.

#694 [16.0][IMP] account_reconcile_oca: Improve multicurrency management
  account_reconcile_analytic_tag/models/account_reconcile_abstract.py
  account_reconcile_oca/models/account_account_reconcile.py
  account_reconcile_oca/models/account_bank_statement_line.py
  account_reconcile_oca/models/account_reconcile_abstract.py
  account_reconcile_oca/static/src/js/widgets/reconcile_data_widget.esm.js
  account_reconcile_oca/static/src/xml/reconcile.xml
  account_reconcile_oca/tests/test_bank_account_reconcile.py
Labels: bot is merging ⏳

#776 [16.0][IMP] account_reconcile_analytic_tag: Using the _get_write_off_move_move_line_dict() method
  account_reconcile_analytic_tag/models/account_reconcile_model.py
Labels: bot is merging ⏳

#651 [16.0][FIX] account_mass_reconcile: reconciles not being sorted
  account_mass_reconcile/models/mass_reconcile.py
Labels: approved, bot is merging ⏳, stale

#778 [16.0][FIX] account_reconcile_oca: missing this.form_controller
  account_reconcile_oca/static/src/js/reconcile/reconcile_controller.esm.js
Labels: approved, bot is merging ⏳

#780 [17.0][MIG] account_reconcile_oca: Missing this.form_controller
  account_reconcile_oca/static/src/js/reconcile/reconcile_controller.esm.js
Labels: bot is merging ⏳

#782 [16.0][FIX] account_reconcile_oca: Add context key skip_account_move_synchronization to avoid side effects
  account_reconcile_oca/views/account_bank_statement_line.xml
Labels: approved, bot is merging ⏳

#783 [16][account_reconcile_oca] Revert PR 782
  account_reconcile_oca/views/account_bank_statement_line.xml
Labels: bot is merging ⏳

#787 [16][FIX] account_reconcile_oca : Wrong amount currency compute in case of change in liquidity line
  account_reconcile_oca/models/account_bank_statement_line.py
  account_reconcile_oca/tests/test_bank_account_reconcile.py
Labels: approved, bot is merging ⏳

#790 [17.0][IMP] account_reconcile_model_oca: Create _get_write_off_move_move_line_dict() method to allow extension
  account_reconcile_model_oca/models/account_reconcile_model.py
Labels: bot is merging ⏳
